### ISSUE TITLE
Split ABC and descendant classes into different files

### ISSUE THREAD

**Issue by stevenhwu** [ComputationalAgronomy/eDNA_bioinformatics_pipeline#10]
![image](https://github.com/ComputationalAgronomy/eDNA_bioinformatics_pipeline/assets/1005078/00d429d5-6856-4d40-b2dd-19931182bcc3)

- This should be either 3 or 5 files
- Figure out the difference between two classes with the same name, and decide if you want to make 2 separate classes with different names, or A inheritance from B
 
![image](https://github.com/ComputationalAgronomy/eDNA_bioinformatics_pipeline/assets/1005078/1edcc892-e491-49af-940f-8778e4e5f90b)

**Comment by ShawnChen09** [comment]
i think i will discard  these two files and  replace them with the "analysis pipeline" folder , is this proper?

**Comment by stevenhwu** [comment]
Ya, tag these with deprecate
